server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 143934762909-4lor476h7nu2i6murt30s469r3oi4p6r.apps.googleusercontent.com
            client-secret: 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
